### ISSUE TITLE
Use bundle image in CI to deploy Operator

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/kepler-operator#104]
Since Operator is deployed in OpenShift using OLM, it is best to test if the operator deployment works as expected using 
`opeators-sdk run bundle` which deploys the operator and sets up the RBAC defined in CSV.

**Comment by husky-parul** [comment]
@sthaha 
We couldn't incorporate this test because we didn't have an OCP CI environment. Is this going to be part of kepler-operator CI that runs on https://github.com/openshift/openshift-tests-private ?

**Comment by sthaha** [comment]
The idea is to run `operator-sdk olm install` to setup OLM on kind and then use `make bundle bundle-image bundle-push` to push images to local registry, use  `operator-sdk run bundle`  to install operator using OLM in the cluster 
See for reference: https://github.com/rhobs/observability-operator/blob/main/.github/e2e-tests-olm/action.yaml#L38

**Comment by husky-parul** [comment]
@sthaha 
I was looking into the e2e test. So the tests get called from 

    go test -v -failfast -timeout $TEST_TIMEOUT ./test/e2e/... --retain=true | tee "$LOGS_DIR/e2e.log" || ret=1

https://github.com/rhobs/observability-operator/blob/23a60b4789520c3c9087c1987a28fa1d637578b7/test/run-e2e.sh#L157

I am curious why we used go for setting up the environments?  Like creating all the resources and setting up the monitoring stack etc...

**Comment by sthaha** [comment]
> I am curious why we used go for setting up the environments? Like creating all the resources and setting up the monitoring stack etc...

Using go to create the resource was only a shortcut since `oc` or `kubectl` would essentially do the same and we already had helpers to do that. I am okay with using a wrapper around `oc | kubectl`.  

Using Go for verification of the resources created is a big win since all assertions are made on static type.
