### ISSUE TITLE
Kepler Operator install issue on ROSA OCP 4.11 cluster

### ISSUE THREAD

**Issue by AdrianHammond** [sustainable-computing-io/kepler-operator#116]
OOM issue seen with the kepler-operator-controller-manager pod when installing the Operator (version 0.5). Pod restarts but than goes into CrashBackLoopOff again and OOM. Operator install does not complete. This is customer environment on ROSA (OCP 4.11.34).

```console
   Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
```

I have tried Operator install on demo.redhat.com ROSA cluster and install is success. 

I have oc describe output of the pod and also events that I can share.

**Comment by AdrianHammond** [comment]
My testing was on a 4.13.4 ROSA cluster

**Comment by sthaha** [comment]
@AdrianHammond could you please help  if the latest changes to the code improves this? The changes to the operator should ideally consume less memory now.
 
An easy way to test this is to run this bundle, if you have `operator-sdk` install locally

```
operator-sdk run bundle quay.io/sthaha/kepler-operator-bundle:0.5.0-dev --install-mode AllNamespaces --namespace=openshift-operators
```

**Comment by AdrianHammond** [comment]
Hi @sthaha 

The customer has tested and they see the following conditions:

1. Kepler operator pod is running.
2. The Operator is in pending state.
3. There is an error ‘RequirementsNotMet’ in events.

**Comment by sthaha** [comment]
@AdrianHammond was that on fresh install of Kepler? I am guessing it is not. Since we broke the API (for good reasons) a complete uninstall of the old version is necessary - https://olm.operatorframework.io/docs/tasks/uninstall-operator/

**Comment by sthaha** [comment]
@husky-parul , This is going to be a common experience for everyone upgrading to 0.6.0. I think we should have a script that cleans up 0.5.0. WDYT?

**Comment by husky-parul** [comment]
We have yet to test the operator on ROSA to document the steps. But the refactored operator should work on 4.13.4 ROSA I will take this up.

**Comment by sthaha** [comment]
@AdrianHammond , I am going to close this as resolved. The latest refactor has also fixed the OOM by reducing the amount of memory required,  significantly.

**Comment by AdrianHammond** [comment]
Thanks @sthaha
