### ISSUE TITLE
make operator show kepler instance related objects

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#120]
After refactoring changes when the Kepler instance is created we don't see in which namespace the daemonset is created. For someone who is unaware of Operator implementation, it isn't easy to know where Kepler exporter pods are running.
If someone deploys Kepler instance from OpenShift UI, he/she should know where related objects are deployed and in which namespace. It will be helpful in case of any debugging issues.
A good example of this would be [clusteroperator](https://github.com/openshift/enhancements/blob/master/dev-guide/cluster-version-operator/dev/clusteroperator.md#related-objects)

**Comment by sthaha** [comment]
Closing this issue since https://github.com/openshift/console/blob/master/frontend/public/components/cluster-settings/related-objects.tsx seems very specific to console-operator.
