### ISSUE TITLE
Create a Make target to build the documentation

### ISSUE THREAD

**Issue by iblancasa** [sustainable-computing-io/kepler-operator#121]
Hi Team,
Thanks for this nice operator! 

It would be awesome if you can add a Makefile target to generate API documentation like the one in the [Tempo Operator](https://github.com/grafana/tempo-operator/blob/main/docs/operator/api.md) or in the [OpenTelemetry Operator](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md).

**Comment by sthaha** [comment]
Great suggestion indeed. Would you like to work on it?

**Comment by sthaha** [comment]
Adding https://github.com/rhobs/observability-operator/blob/main/docs/api.md  as well for reference for auto generated API docs.

**Comment by ramachandranravi** [comment]
Hi @sthaha I can take this one. Pls feel free to assign this task. Thank you!

**Comment by sthaha** [comment]
Thanks for the help @ramachandranravi 🙇

**Comment by ramachandranravi** [comment]
Hi @sthaha PR# submitted via https://github.com/sustainable-computing-io/kepler-operator/pull/205/commits 
Thanks.
