### ISSUE TITLE
Indicate what project Kepler is installed in

### ISSUE THREAD

**Issue by stleerh** [sustainable-computing-io/kepler-operator#173]
When creating the `kepler` custom resource, the Web console does not indicate that this is installed in the `openshift-kepler-operator` project.  This should be mentioned as the only way to know this is to find it in the [doc](https://sustainable-computing.io/installation/community-operator/#install-kepler-community-operator-from-operator-hub).

**Comment by sthaha** [comment]
@stleerh Closing this in favour of https://github.com/sustainable-computing-io/kepler-operator/issues/120 
which will be addressed post Dev-Preview. 

I am ambivalent about this feature since where operator installs resources should be treated as implementation detail.
