### ISSUE TITLE
Cache commonly used binaries in CI

### ISSUE THREAD

**Issue by sthaha** [sustainable-computing-io/kepler-operator#203]
GH CI is starting to fail dowloading binaries 
See: https://github.com/sustainable-computing-io/kepler-operator/actions/runs/6071218125/job/16468811589?pr=201#step:4:142
```
Flag --short has been deprecated, and will be removed in the future.
 🔔 installing kustomize version: v3.8.7
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
 ❌ FAIL: failed to install kustomize
make: *** [Makefile:201: kustomize] Error 1
```

We don't need to download binaries every time if we cache them. E.g https://github.com/rhobs/observability-operator/blob/main/.github/tools-cache/action.yaml 

This should also improve both the stability and  the time taken by CI as well.

**Comment by sthaha** [comment]
@sbdtu5498 thank you for helping you 🙇 . Please note we already have `make tools` to help with the installation of required binaries to `tmp/bin`

**Comment by sthaha** [comment]
Reassigning this to @vprashar2929 since we have #278  from him.

**Comment by vprashar2929** [comment]
Closing as #282 is merged
