### ISSUE TITLE
Enhance OpenShift dashboard for Kepler

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#246]
The current [JSON](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/pkg/components/exporter/assets/kepler-dashboard.json) for the OpenShift dashboard lacks some functionality and needs updation. 

Panels that can be added:
- [x]  `List of different CPU architecture with a number of nodes`: Computed via:
```
sum by (cpu_architecture)(kepler_node_info) 
```
- [x]  `Total Energy Consumption`: Computed via:
```
 sum(sum by (container_namespace) (
  (increase(kepler_container_joules_total{container_namespace=~".*"}[1h])
    * $watt_per_second_to_kWh
  ) *
  (count_over_time(kepler_container_joules_total{container_namespace=~".*"}[24h])/
    count_over_time(kepler_container_joules_total{container_namespace=~".*"}[1h])
  )
))
```
- [x]  `Total Kepler Pods`: Computed via:
```
sum(kepler_node_info)
```

Existing panels that need updation:

- [x] `Pod/Process Power Consumption (W)`: The panels can be broken down on the basis of the type of process `Pod/Process (PKG) Power Consumption (W)` can be one panel and `Pod/Process (DRAM) Power Consumption (W)` can be another and so on. 
- [x]  `Power Consumption (W) of Top10 processes`: Should be renamed to `Total Power Consumption (W) in Namespace`
- [x]  `Total Power Consumption (kWh per day) of Top10 processes`: Should be renamed to `Total Power Consumption (kWh per day) in Namespace`
- [x]  `Total Power Consumption for Namespace: (kWh per day)`:
  - [x]  Should be renamed to `Total Power Consumption for Top 10 Namespaces (kWh per day)`
  - [x]  Query used in the panel should reflect all namespace i.e. `{container_namespace=~"$namespace"}` should be `{container_namespace=~".*"}`
  - [x]  Table should list 10 namespaces and their corresponding power consumption
  - [x]  If possible add this panel at the start instead of the bottom.

**Comment by vimalk78** [comment]
@vprashar2929  converted the asked items into a checklist. based on PRs getting merged, we can close the tasks and refer the corresponding commit/PR

**Comment by vprashar2929** [comment]
Thanks @vimalk78 🙂

**Comment by sthaha** [comment]
@vprashar2929 I am closing this, please feel free to reopen if you disagree.
