### ISSUE TITLE
GitHub Action Failing to push image to quay.io

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler-operator#25]
To be able to push image to quay we need bot token in https://quay.io/repository/sustainable_computing_io/kepler-operator to be used by GH Actions. Need admin access to  https://quay.io/repository/sustainable_computing_io/kepler-operator

![image](https://user-images.githubusercontent.com/24639524/208951633-e33df6d4-dbf2-4cb7-9c85-97ca2f24eb32.png)

**Comment by rootfs** [comment]
the bot name and token are setup for the repo, please use `BOT_NAME` and `BOT_TOKEN` env to push images

**Comment by husky-parul** [comment]
### Issue Description 

GitHub action fails to push image to quay.io using[ Repository secrets](https://github.com/sustainable-computing-io/kepler-operator/settings/secrets/actions) `BOT_NAME` and `BOT_TOKEN` 

![image](https://user-images.githubusercontent.com/24639524/214066278-71122729-62f3-4ffa-8eea-c1eb793ac383.png)

Example workflow: https://github.com/sustainable-computing-io/kepler-operator/actions/runs/3961813873/jobs/6787797431#step:2:16

@rootfs @SamYuan1990

**Comment by SamYuan1990** [comment]
> ### Issue Description
> GitHub action fails to push image to quay.io using[ Repository secrets](https://github.com/sustainable-computing-io/kepler-operator/settings/secrets/actions) `BOT_NAME` and `BOT_TOKEN`
> 
> ![image](https://user-images.githubusercontent.com/24639524/214066278-71122729-62f3-4ffa-8eea-c1eb793ac383.png)
> 
> Example workflow: https://github.com/sustainable-computing-io/kepler-operator/actions/runs/3961813873/jobs/6787797431#step:2:16
> 
> @rootfs @SamYuan1990

wait a min, it's CI job, hence push CI build result to repository?

**Comment by husky-parul** [comment]
Yes. I found something similar here, https://docs.github.com/en/actions/security-guides/encrypted-secrets
```
For secrets stored at the environment level, you can enable required reviewers to control access to the secrets.
A workflow job cannot access environment secrets until approval is granted by required approvers.
```

**Comment by husky-parul** [comment]
Going to test it with `push`

**Comment by husky-parul** [comment]
resolved in https://github.com/sustainable-computing-io/kepler-operator/pull/39
