### ISSUE TITLE
No space left when running e2e tests on GH actions runner

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#257]
While running e2e tests on GH runner it appears that workflow sometimes fails because of no space left on device

See the below CI run:
https://github.com/sustainable-computing-io/kepler-operator/actions/runs/6342734646/job/17229177042?pr=256#step:8:142

**Comment by sthaha** [comment]
https://github.com/sustainable-computing-io/kepler-operator/pull/258 has the fix for it :)

**Comment by vprashar2929** [comment]
Closing as #258 merged
