### ISSUE TITLE
Running local-cluster using  `make cluster-up` fails when kind is not pre-installed

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler-operator#259]
I encountered this issue when reviewing the [PR](https://github.com/sustainable-computing-io/kepler-doc/pull/106/files)

When I run make cluster-up I see the following
```
 🔆🔆🔆  Ensuring all tools are installed  🔆🔆🔆 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 🔔 installing all tools ...
 🔔 installing controller-gen with version: v0.12.1
go: downloading sigs.k8s.io/controller-tools v0.12.1
go: downloading github.com/spf13/cobra v1.7.0
go: downloading k8s.io/api v0.27.1
go: downloading k8s.io/apimachinery v0.27.1
```

But the command failed on a machine with no pre-installed kind

Starting kind with cluster name `kind`
```
 ❯ kind create cluster --name=kind -v6 --config=/home/parsingh/go/src/github.com/test-pr/kepler-operator/tmp/local-dev-cluster/tmp/kind/kind.yml

/home/parsingh/go/src/github.com/test-pr/kepler-operator/tmp/local-dev-cluster/lib/utils.sh: line 50: kind: command not found
make: *** [Makefile:120: cluster-up] Error 127
```

Shouldn't the make command ensures that we have kind pre-installed as well?
I will open a corresponding issue in the kepler-operator

**Comment by vprashar2929** [comment]
For this, I believe we added a [check](https://github.com/sustainable-computing-io/local-dev-cluster/blob/505d244e179e0d235c1590a31e57bf4c5b743b9a/providers/kind/kind.sh#L38C1-L38C22) in local-dev-cluster to validate whether kind is available or not but looks like the check didn't work as expected as I think it found kubectl to be available. Will work on fixing this

**Comment by sthaha** [comment]
closing this as resolved by https://github.com/sustainable-computing-io/local-dev-cluster/pull/50
