### ISSUE TITLE
Set up Model Server Controller Implementation for Operator

### ISSUE THREAD

**Issue by KaiyiLiu1234** [sustainable-computing-io/kepler-operator#30]
The Model Server Controller needs to be tested to ensure all required Kubernetes Objects are set up and working correctly. Unit Tests must also be created for the Model Server Controller logic.

**Comment by rootfs** [comment]
0.5 release

**Comment by KaiyiLiu1234** [comment]
Currently, the Model Server Controller creates all necessary kubernetes objects and properly removes them with finalizers. Unit and integration tests are incomplete. Daemonset containing Model Server Image is not working as expected.

**Comment by KaiyiLiu1234** [comment]
I will close this issue since the operator now has a model server controller implemented. I will reopen if issues related to trainer or exporter persist despite updates to the model server
