### ISSUE TITLE
kepler:kepler:<rules> not working for grafana dashboard

### ISSUE THREAD

**Issue by fnoorden** [sustainable-computing-io/kepler-operator#332]
kepler:kepler:<rules> are not working for the grafana dashboard in hack/dashboard/assets/kepler/dashboard.json,

When I replace "kepler:kepler:"with  a single "kepler:" it will work.

**example:**
Wrong
"expr": "kepler:kepler:container_joules_total:consumed:24h:all * $watt_per_second_to_kWh",
Right
"expr": "kepler:container_joules_total:consumed:24h:all * $watt_per_second_to_kWh",

**Comment by vprashar2929** [comment]
@fnoorden Are you using operator's `release-0.9.2`? If yes then the latest `dashboard.json` might not work as expected since we updated the expression to contain Kepler instance name as well i.e `kepler:<instance_name>:container_joules_total....`

**Comment by fnoorden** [comment]
@vprashar2929  That's correct, I am using kepler-operator v0.9.2 from dev-preview channel. 

Should I use a different version of the operator?

**Comment by vprashar2929** [comment]
For configuring Grafana as of now you can checkout `v0.9.2` and setup till the time we have the new operator release

**Comment by fnoorden** [comment]
Thx a lot
