### ISSUE TITLE
Operator doesn't reconcile Kepler when redfish related properties are changed

### ISSUE THREAD

**Issue by vprashar2929** [sustainable-computing-io/kepler-operator#377]
When redfish-related properties are changed Kepler doesn't get reconciled and pods are not terminated to reflect the new properties changes. Changing either `probeInterval` or `skipSSLVerify` doesn't result in Kepler pods relaunch. Hence new config changes are not read by Kepler.

**Comment by sthaha** [comment]
Addressed by #378

**Comment by vprashar2929** [comment]
closing as #378 is merged
