### ISSUE TITLE
Docker required to run Makefile on kepler-operator

### ISSUE THREAD

**Issue by arthurus-rex** [sustainable-computing-io/kepler-operator#405]
Following the steps in [the docs](https://sustainable-computing.io/installation/kepler-operator/), running `make cluster-up` on a system that has podman installed instead of docker, we receive the following error:

```
~/go/src/github.com/kepler-operator/tmp/local-dev-cluster/lib/utils.sh: line 182: docker: command not found
 ❯ docker run -d --restart=always --name kind-registry -p 127.0.0.1:5001:5000 --network kind registry:2

~/go/src/github.com/kepler-operator/tmp/local-dev-cluster/lib/utils.sh: line 51: docker: command not found
make: *** [Makefile:126: cluster-up] Error 127
```
Installing docker alleviates the issue.  Could consider either adding podman compatibility to Makefile, or specifying in docs that docker is required.

**Comment by vprashar2929** [comment]
@arthurus-rex You are correct. The docs should be updated to include `docker` as one of the requirements. Nice find. 
Do you want to update this here: https://github.com/sustainable-computing-io/kepler-doc ?

**Comment by arthurus-rex** [comment]
Yes of course, I will gladly update this, thank you for your prompt response!

**Comment by vprashar2929** [comment]
closing as https://github.com/sustainable-computing-io/kepler-doc/pull/160 got merged
