### ISSUE TITLE
kepler not monitoring power.

### ISSUE THREAD

**Issue by MUSTAFA-A-KHAN** [sustainable-computing-io/kepler-operator#423]
I have installed kepler on my ocp cluster to monitor the power overview but its not generating any values.
```
Total Energy Consumption (kWh) - Last 24 hours

-
kWh

```

**Comment by vprashar2929** [comment]
@MUSTAFA-A-KHAN Can you provide more details on this? Specifically, how did you install the operator, what version of the OCP are you running and is the UWM enabled on the cluster?

**Comment by MUSTAFA-A-KHAN** [comment]
I have installed the Kepler using operator hub.

**Comment by vprashar2929** [comment]
@MUSTAFA-A-KHAN Have you enabled UWM on the cluster? https://docs.openshift.com/container-platform/4.15/observability/monitoring/enabling-monitoring-for-user-defined-projects.html

**Comment by MUSTAFA-A-KHAN** [comment]
Thanks it's working now.
