### ISSUE TITLE
promethus dashboard in grafana reporting errors after running deploy-grafana.sh script

### ISSUE THREAD

**Issue by ramachandranravi** [sustainable-computing-io/kepler-operator#439]
tested using deploy-grafana.sh script in OCP 4.16.z version. This script creates two dashboards [here](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/hack/dashboard/openshift/deploy-grafana.sh#L284-L289). kepler-dasboard seems to work well however Prometheus dashboard metrics are not seen in the dashboard reporting errors like "Failed to update Legacy queries". Attached screenshot.

![image](https://github.com/user-attachments/assets/1cba82ee-5015-4034-8749-ded275fd7f8a)

**Comment by vprashar2929** [comment]
@ramachandranravi Are we good to close this post https://github.com/sustainable-computing-io/kepler-operator/pull/438 ?

**Comment by ramachandranravi** [comment]
@vprashar2929 This issue still persists and has to be fixed.

**Comment by vprashar2929** [comment]
I see, Can you try this https://github.com/sustainable-computing-io/kepler-operator/pull/441 and see if it fixes the issue?

**Comment by ramachandranravi** [comment]
I tried the changes provided in #441 but it didn't work. I still see the same result.

![image](https://github.com/user-attachments/assets/6cf4d98b-a13e-4cc7-b6c5-3665715fb361)

**Comment by vprashar2929** [comment]
@ramachandranravi My bad 😞 I forgot to add the variable in the dashboard. I have updated the PR. Can you again try

**Comment by ramachandranravi** [comment]
@vprashar2929 It works now. changes can be committed to the master branch.  Thanks!

![image](https://github.com/user-attachments/assets/3123de0c-dcf9-4ac6-81e1-12cb2e713d0d)

**Comment by ramachandranravi** [comment]
https://github.com/sustainable-computing-io/kepler-operator/pull/441 addresses the issue. Closing it here.
