### ISSUE TITLE
Conflict between Kepler-exporter and OVN Kubernetes

### ISSUE THREAD

**Issue by novacain1** [sustainable-computing-io/kepler-operator#51]
Similar problem as exhibited in https://github.com/sustainable-computing-io/kepler/issues/527.  the Kepler Operator hardcodes the host port to 9102/tcp, which won't work in an environment that uses OVN kubernetes as a CNI.

@chr15p fyi and who I believe will open a PR here.

**Comment by husky-parul** [comment]
Thank you for reporting this. Atm the port is set by the operator and therefore cannot be configured. We want to export it as feild in the CRD which needs to be addressed this as a bug fix PR. I am working on it.

Question. Are you installing the operator via make  or using operator hub? If make  is being used we can address this faster 
(while I am working on the PR). 
Once you've cloned our repo, in the controller https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/controllers/kepler_controller.go search/replace 9102 your desired port and use the same steps with make  to run and test the operator.

**Comment by novacain1** [comment]
Hi, it looks like https://github.com/sustainable-computing-io/kepler-operator/pull/52 changed the port from 9102 to 9103 (among other things).  Sadly, 9103/tcp is used by ovn-kubernetes-node in Single Node OpenShift (SNO).

Any word on https://github.com/sustainable-computing-io/kepler-operator/pull/53, which attempts to remove the host port requirement?

**Comment by rootfs** [comment]
@novacain1 can you rebase #53?

**Comment by rootfs** [comment]
@novacain1 the port is settable in the API (see https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/config/samples/kepler.system_v1alpha1_kepler.yaml#L16). You can provide a new port to reset the default 9103

**Comment by novacain1** [comment]
hey @rootfs, this is working for me in release-0.4 with `collectorPort: 9106` overridden in config/samples/kepler.system_v1alpha1_kepler.yaml.  Thank you.

I'll see about rebaseing the PR to address the HostPort observations.

**Comment by rootfs** [comment]
@novacain1 trouble shooting PR welcome :D https://github.com/sustainable-computing-io/kepler-doc/blob/main/docs/usage/trouble_shooting.md

**Comment by husky-parul** [comment]
fixed. the collector port can be configure from the CR
