### ISSUE TITLE
Add namespace property to Kepler CR

### ISSUE THREAD

**Issue by husky-parul** [sustainable-computing-io/kepler-operator#93]
In Web console, install Kepler operator.  Go to Operators > Installed Operators.  On the Kepler row, click the "Kepler" link and then Create Kepler.  In Form view, there should be a field to specify the namespace.  This namespace should be created if it doesn't exist.

The current behavior is it will create the Kepler CR in the selected project.  This is by default, openshift-operators, which is not where you want it to be installed.  If you switch to YAML view, the namespace field indicates it will be installed in openshift-operators.  However, you can't change it to something like "kepler", because the namespace must already exist.

Let's use this issue to discuss https://issues.redhat.com/browse/POWERMON-84 reported by @stleerh and finalize the next steps.

**Comment by sthaha** [comment]
@husky-parul 
What would be the consequence of changing the namespace property ? 

Given that we want to make the CRD cluster scoped, I think we shouldn't introduce a namespace property instead use a generated namespace or a hardcoded one and add that information in the status of the CR.

**Comment by husky-parul** [comment]
Yes I agree but I have created this issue to discuss https://issues.redhat.com/browse/POWERMON-84 reported by @stleerh
We can use this thread to finalize the next steps.

@sthaha

**Comment by sthaha** [comment]
The issue in POWERMON-84 is the default/expected behaviour for any operator installed through OLM. Here is my initial thought 
* we should first convert the CRD to clusterscoped - this is semantically correct. This also removes the need for a `namespace`
* Any CR other than with the name *kepler* ( or pick an name) will have a status set to "invalid" indicating that operator will not reconcile it 
* For deployment of kepler, operator will need to create a namespace ( I think we can hardcode it to openshift-kepler ) 
* All resources will created in that namespace 
* Operator will update the status of `kepler`  CR to indicate `namespace: openshift-kepler` 
*

**Comment by husky-parul** [comment]
There are two threads to this discussion.

**Should the kepler-operator be namespaced or cluster scope?**
According to [operator-sdk doc](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#:~:text=A%20namespace%2Dscoped%20operator%20watches,be%20created%20in%20any%20Namespace.)

> An operator should be cluster-scoped if it watches resources that can be created in any Namespace

`kepler-operator` doesn't watches resources across namespace from an operator point of view, meaning reconcilalation and upgrades. However it does collects metrics for all pods in all namespaces. 

That said it also mentions:
>By default, operator-sdk init scaffolds a cluster-scoped operator. 

This is why I mentioned that the current operator should be clusterscoped because I didn't change the default settings.


**What is the current state of the operator?**
The current operator in `go` code seems to be clusterscoped (operator-sdk default settings).

1. According to the [doc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) is initialized with no Namespace option specified, or Namespace: "" will watch all Namespaces)

> A Manager is initialized with no Namespace option specified, or Namespace: "" will watch all Namespaces:

[kepler manager](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/main.go#L79) uses `Namespace:  "",`

2. The operator creates `ClusterRole` and `ClusterRoleBinding` instead of `Role` and `Roleinding`. [doc](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#restricting-roles-and-permissions)
https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/config/rbac/role.yaml

3. `controller` should have RBAC markers for clusterscope [doc](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#changing-the-permissions-to-namespaced)
[kepler-operator code](https://github.com/sustainable-computing-io/kepler-operator/blob/v1alpha1/controllers/kepler_controller.go#L85)

4. Watching resources in all Namespaces (default)
Only the AllNamespaces install mode is supported: true by default [doc](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#watching-resources-in-all-namespaces-default-1) in the `csv` file under `spec.installModes`

kepler-operator [csv file](https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/kepler-operator/0.5.0/manifests/kepler-operator.v0.5.0.clusterserviceversion.yaml#L321)
```
installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
```

Based on the above information, the operator sshould be `clusterscoped` but it is not behaving as one and we need to investigate the reason.

@sthaha

**Comment by husky-parul** [comment]
I am going to test 1 & 2 i.e remove `Namespace:  "",` from the `manager` and change the csv file to only 
```
installModes:
 - supported: true
    type: AllNamespaces
```

**Comment by sthaha** [comment]
@husky-parul there is a difference between the operator being cluster-scoped vs the CRD that is cluster-scope. The point I am trying to allude to is that the `Kepler` CRD should be clusterscoped and the operator must be configured to watch only one singe instance of that CRD. What this also entails is that the operator watching a CRD that is not namespaced, will need clusterroles and clusterrolebindings and use `Namespace: ""`

**Comment by sthaha** [comment]
> kepler-operator doesn't watches resources across namespace from an operator point of view, meaning reconcilalation and upgrades. However it does collects metrics for all pods in all namespaces.

Thats isn't true because the operator as it currently stands does watch `Kepler` instances being created in *any* namespace and thus cluster-scoped.

**Comment by sthaha** [comment]
I have created #99 which should take care of this issue as well.
